$ErrorActionPreference = 'Stop'

$repo = Join-Path $PSScriptRoot 'upstream\pico-faces'
$zigCommand = Get-Command zig -ErrorAction SilentlyContinue

if ($zigCommand) {
    $zig = $zigCommand.Source
} else {
    $packageRoot = Join-Path $env:LOCALAPPDATA 'Microsoft\WinGet\Packages'
    $package = Get-ChildItem $packageRoot -Directory -ErrorAction SilentlyContinue |
        Where-Object Name -Like 'zig.zig_*' |
        Select-Object -First 1
    $zig = Get-ChildItem $package.FullName -Filter 'zig.exe' -Recurse -ErrorAction SilentlyContinue |
        Select-Object -First 1 -ExpandProperty FullName
}

if (-not $zig) {
    throw 'Zig was not found. Open a new terminal after installation and try again.'
}

Push-Location $repo
try {
    New-Item -ItemType Directory -Force 'build\m3_long_cfg\e2e' | Out-Null

    $sources = @(
        'engine/desktop/main_golden.c'
        'engine/src/graph.c'
        'engine/src/dit.c'
        'engine/src/vae_dec.c'
        'engine/src/kernels_ref.c'
        'engine/src/prng.c'
    )
    $compileArguments = @(
        'cc'
        '-O2'
        '-Wall'
        '-Wextra'
        '-Icheckpoints/m3_long_cfg'
        '-Iengine/include'
    ) + $sources + @('-o', 'build/m3_long_cfg/rf_golden.exe')

    & $zig @compileArguments
    if ($LASTEXITCODE -ne 0) {
        throw "Compilation failed with exit code $LASTEXITCODE"
    }

    & '.\build\m3_long_cfg\rf_golden.exe' `
        'checkpoints\m3_long_cfg\model.bin' `
        'build\m3_long_cfg\e2e' `
        4 `
        1
    if ($LASTEXITCODE -ne 0) {
        throw "Generation failed with exit code $LASTEXITCODE"
    }

    $generatedPath = Resolve-Path 'build\m3_long_cfg\e2e\eng_1.rgb'
    $goldenPath = Resolve-Path 'checkpoints\m3_long_cfg\goldens\golden_1.rgb'
    $generated = [System.IO.File]::ReadAllBytes($generatedPath)
    $golden = [System.IO.File]::ReadAllBytes($goldenPath)
    $matches = [System.Linq.Enumerable]::SequenceEqual($generated, $golden)

    Write-Host "generated bytes: $($generated.Length)"
    Write-Host "golden bytes:    $($golden.Length)"
    Write-Host "byte-exact:      $matches"
    Get-FileHash $generatedPath -Algorithm SHA256
    Get-FileHash $goldenPath -Algorithm SHA256

    if (-not $matches) {
        throw 'Generated output does not match the released golden output.'
    }
} finally {
    Pop-Location
}
